<?php
$root=dirname(__DIR__).'/eduflow-core/';$service=file_get_contents($root.'includes/class-migration-service.php');$adapter=file_get_contents($root.'includes/class-legacy-adapter.php');$db=file_get_contents($root.'includes/class-db.php');$admin=file_get_contents($root.'admin/class-migration-admin.php');$boot=file_get_contents($root.'eduflow-core.php');$all=$service.$adapter.$db.$admin.$boot;
$checks=array(
'phase 7 retained'=>str_contains($boot,'class-migration-service.php'),
'defensive detection'=>str_contains($service,"SHOW TABLES LIKE %s")&&str_contains($service,'manual adapter mapping required'),
'missing source safety'=>str_contains($service,'legacy_source_unavailable'),
'read only adapter'=>!preg_match('/(UPDATE|DELETE|TRUNCATE|ALTER|DROP) `\'.esc_sql\(\$this->table/',$adapter),
'adapter contract'=>str_contains($adapter,'detect(); public function count()')&&str_contains($adapter,'preview( $offset, $limit )'),
'named adapters'=>substr_count($adapter,'class EduFlow_Legacy_')>=9,
'dry run no import'=>str_contains($service,"if('dry_run'===\$run['mode'])"),
'no dry run id generation'=>!str_contains($service,"EduFlow_ID_Service::generate"),
'mobile normalize'=>str_contains($adapter,'normalize_indian_mobile'),
'missing email allowed'=>!str_contains($adapter,'Missing email'),
'name matching prohibited'=>str_contains($service,'names are not used for automatic merging'),
'ambiguous identity conflict'=>str_contains($service,'Multiple strong identity matches'),
'map lookup priority'=>str_contains($service,'SELECT * FROM $map WHERE institute_id=%d'),
'mapping uniqueness'=>str_contains($db,'UNIQUE KEY legacy_record'),
'fingerprinting'=>str_contains($service,"hash('sha256'")&&str_contains($db,'source_fingerprint char(64)'),
'payment callback conservative'=>str_contains($adapter,'import_callback')&&!str_contains($service,"verification_status'=>'verified'"),
'no google creation'=>!str_contains($service,'EduFlow_Google_Service::queue'),
'demo retained'=>str_contains($service,"'demo_session','demo_booking'"),
'resumable cursor'=>str_contains($service,"'cursor_value'=>\$next")&&str_contains($service,'migration_resumed'),
'backup required'=>str_contains($service,'backup_confirmation_required')&&str_contains($admin,'Backup confirmed'),
'conflict table'=>str_contains($db,'CREATE TABLE $migration_conflicts'),
'resolution audit'=>str_contains($service,'migration_conflict_resolved'),
'institute scope'=>substr_count($service,'institute_id=%d')>=8,
'capability'=>str_contains($admin,"current_user_can('eduflow_manage_reports')"),
'nonce'=>substr_count($admin,'check_admin_referer')===3,
'no public rest'=>!str_contains(file_get_contents($root.'includes/class-rest.php'),'migration'),
'no destructive mode'=>!str_contains(strtolower($all),'replace everything'),
'no fake emails'=>!preg_match('/[a-z0-9]+@(example|invalid)\./i',$all),
'no sheets'=>!preg_match('/sheets\.googleapis|spreadsheets/i',$all),
);
foreach($checks as$name=>$ok){if(!$ok){fwrite(STDERR,"Failed Phase 7: $name\n");exit(1);}}echo count($checks)." Phase 7 assertions passed\n";
