<?php
// Local security/domain checks only; no request is sent to Google.
define('ABSPATH',__DIR__);define('AUTH_KEY','test-auth-key');define('SECURE_AUTH_KEY','test-secure-key');define('MINUTE_IN_SECONDS',60);
class WP_Error {private $code;private $message;private $data;public function __construct($code,$message='',$data=null){$this->code=$code;$this->message=$message;$this->data=$data;}public function get_error_code(){return $this->code;}public function get_error_message(){return $this->message;}}
function is_wp_error($v){return $v instanceof WP_Error;}function site_url(){return 'https://local.test';}function absint($v){return abs((int)$v);}function sanitize_text_field($v){return trim((string)$v);}function sanitize_email($v){return filter_var((string)$v,FILTER_SANITIZE_EMAIL);}function is_email($v){return false!==filter_var($v,FILTER_VALIDATE_EMAIL);}function esc_url_raw($v){return filter_var($v,FILTER_SANITIZE_URL);}function get_current_user_id(){return 17;}
$GLOBALS['transients']=array();function set_transient($k,$v,$ttl){$GLOBALS['transients'][$k]=$v;}function get_transient($k){return $GLOBALS['transients'][$k]??false;}function delete_transient($k){unset($GLOBALS['transients'][$k]);}
class EduFlow_Settings {public static function institute_db_id(){return 9;}}
require dirname(__DIR__).'/eduflow-core/includes/class-crypto-service.php';require dirname(__DIR__).'/eduflow-core/includes/class-google-service.php';require dirname(__DIR__).'/eduflow-core/includes/class-audit-service.php';
$secret='client-secret-value';$cipher=EduFlow_Crypto_Service::encrypt($secret);$checks=array(!is_wp_error($cipher),$cipher!==$secret,strpos($cipher,$secret)===false,EduFlow_Crypto_Service::decrypt($cipher)===$secret);
$state='one-time-oauth-state';set_transient('eduflow_google_state_'.hash('sha256',$state),array('user_id'=>17,'institute_id'=>9),600);$checks[]=is_array(EduFlow_Google_Service::validate_state($state));$checks[]=is_wp_error(EduFlow_Google_Service::validate_state($state));
$attendees=EduFlow_Google_Service::valid_attendees(array('Teacher@Example.com','','invalid','teacher@example.com','student@example.com'));$checks[]=count($attendees)===2;$checks[]=$attendees[0]['email']==='teacher@example.com';
$key1=EduFlow_Google_Service::conference_request_id(9,'YTC-CLS-000001');$key2=EduFlow_Google_Service::conference_request_id(9,'YTC-CLS-000001');$checks[]=$key1===$key2&&strlen($key1)===64;
$db=file_get_contents(dirname(__DIR__).'/eduflow-core/includes/class-db.php');$checks[]=strpos($db,'UNIQUE KEY institute_lecture (institute_id,lecture_id)')!==false;$checks[]=strpos($db,'UNIQUE KEY sync_key (sync_key)')!==false;foreach(array('integrations','google_events','teachers','batches','batch_students','classes','schedule_rules') as $table_name){$checks[]=strpos($db,"self::table( '$table_name' )")!==false;}$redact=new ReflectionMethod('EduFlow_Audit_Service','redact');$redact->setAccessible(true);$safe=$redact->invoke(null,array('client_secret'=>'secret','refresh_token'=>'token','normal'=>'ok'));$checks[]=$safe['client_secret']==='[REDACTED]'&&$safe['refresh_token']==='[REDACTED]'&&$safe['normal']==='ok';
$google=file_get_contents(dirname(__DIR__).'/eduflow-core/includes/class-google-service.php');$checks[]=strpos($google,"if(\$map['google_event_id'])")!==false;$checks[]=strpos($google,"'conferenceData'=>array('createRequest'")!==false;$checks[]=stripos($google,'sheets.googleapis.com')===false;
foreach($checks as $i=>$ok){if(!$ok){fwrite(STDERR,'Failed Phase 4 check '.($i+1).PHP_EOL);exit(1);}}echo count($checks)." Phase 4 assertions passed\n";
