<?php
defined( 'ABSPATH' ) || exit;

final class EduFlow_DB {
	public static function table( $name ) {
		global $wpdb;
		$allowed = array( 'institutes', 'id_sequences', 'audit_log', 'settings', 'migration_map', 'migration_runs', 'migration_conflicts', 'jobs', 'admissions', 'students', 'payments', 'access', 'access_history', 'teachers', 'batches', 'batch_students', 'classes', 'schedule_rules', 'integrations', 'google_events', 'demo_sessions', 'demo_bookings', 'user_links', 'notifications', 'attendance' );
		if ( ! in_array( $name, $allowed, true ) ) {
			throw new InvalidArgumentException( 'Unknown EduFlow table.' );
		}
		return $wpdb->prefix . 'eduflow_' . $name;
	}

	public static function tables() {
		return array_map( array( __CLASS__, 'table' ), array( 'institutes', 'id_sequences', 'audit_log', 'settings', 'migration_map', 'migration_runs', 'migration_conflicts', 'jobs', 'admissions', 'students', 'payments', 'access', 'access_history', 'teachers', 'batches', 'batch_students', 'classes', 'schedule_rules', 'integrations', 'google_events', 'demo_sessions', 'demo_bookings', 'user_links', 'notifications', 'attendance' ) );
	}

	public static function install() {
		global $wpdb;
		require_once ABSPATH . 'wp-admin/includes/upgrade.php';
		$c = $wpdb->get_charset_collate();
		$i = self::table( 'institutes' ); $s = self::table( 'id_sequences' ); $a = self::table( 'audit_log' );
		$st = self::table( 'settings' ); $m = self::table( 'migration_map' ); $j = self::table( 'jobs' );
		$ad = self::table( 'admissions' ); $students = self::table( 'students' ); $payments = self::table( 'payments' );
		$access = self::table( 'access' ); $history = self::table( 'access_history' ); $teachers = self::table( 'teachers' );
		$batches = self::table( 'batches' ); $batch_students = self::table( 'batch_students' ); $classes = self::table( 'classes' );
		$rules = self::table( 'schedule_rules' ); $integrations = self::table( 'integrations' ); $google_events = self::table( 'google_events' );
		$demo_sessions = self::table( 'demo_sessions' ); $demo_bookings = self::table( 'demo_bookings' );
		$user_links = self::table( 'user_links' ); $notifications = self::table( 'notifications' );
		$attendance = self::table( 'attendance' );
		$migration_runs = self::table( 'migration_runs' ); $migration_conflicts = self::table( 'migration_conflicts' );
		$sql = array(
			"CREATE TABLE $i (id bigint unsigned NOT NULL AUTO_INCREMENT, institute_key varchar(64) NOT NULL, name varchar(190) NOT NULL, status varchar(20) NOT NULL DEFAULT 'active', created_at datetime NOT NULL, updated_at datetime NOT NULL, PRIMARY KEY (id), UNIQUE KEY institute_key (institute_key), KEY status (status)) $c;",
			"CREATE TABLE $s (id bigint unsigned NOT NULL AUTO_INCREMENT, institute_id bigint unsigned NOT NULL, sequence_type varchar(20) NOT NULL, current_value bigint unsigned NOT NULL DEFAULT 0, status varchar(20) NOT NULL DEFAULT 'active', created_at datetime NOT NULL, updated_at datetime NOT NULL, PRIMARY KEY (id), UNIQUE KEY institute_type (institute_id,sequence_type), KEY status (status)) $c;",
			"CREATE TABLE $a (id bigint unsigned NOT NULL AUTO_INCREMENT, institute_id bigint unsigned NULL, user_id bigint unsigned NULL, action varchar(100) NOT NULL, entity_type varchar(80) NOT NULL, entity_id varchar(100) NULL, old_value longtext NULL, new_value longtext NULL, ip_address varchar(45) NULL, status varchar(20) NOT NULL DEFAULT 'recorded', created_at datetime NOT NULL, PRIMARY KEY (id), KEY institute_created (institute_id,created_at), KEY entity (entity_type,entity_id), KEY user_id (user_id)) $c;",
			"CREATE TABLE $st (id bigint unsigned NOT NULL AUTO_INCREMENT, institute_id bigint unsigned NOT NULL, setting_key varchar(100) NOT NULL, setting_value longtext NULL, status varchar(20) NOT NULL DEFAULT 'active', created_at datetime NOT NULL, updated_at datetime NOT NULL, PRIMARY KEY (id), UNIQUE KEY institute_setting (institute_id,setting_key), KEY status (status)) $c;",
			"CREATE TABLE $m (id bigint unsigned NOT NULL AUTO_INCREMENT, institute_id bigint unsigned NOT NULL, legacy_source varchar(100) NOT NULL, legacy_table varchar(190) NOT NULL, legacy_id varchar(190) NOT NULL, new_entity varchar(80) NOT NULL, new_id varchar(100) NULL, target_db_id bigint unsigned NULL, source_fingerprint char(64) NULL, migration_status varchar(30) NOT NULL DEFAULT 'detected', migrated_at datetime NULL, created_at datetime NOT NULL, updated_at datetime NOT NULL, PRIMARY KEY (id), UNIQUE KEY legacy_record (institute_id,legacy_source,legacy_table,legacy_id), KEY new_record (new_entity,new_id), KEY target_db_id (target_db_id), KEY source_fingerprint (source_fingerprint), KEY migration_status (migration_status)) $c;",
			"CREATE TABLE $j (id bigint unsigned NOT NULL AUTO_INCREMENT, institute_id bigint unsigned NULL, job_type varchar(100) NOT NULL, idempotency_key varchar(190) NOT NULL, payload longtext NULL, status varchar(20) NOT NULL DEFAULT 'pending', attempts smallint unsigned NOT NULL DEFAULT 0, available_at datetime NOT NULL, started_at datetime NULL, completed_at datetime NULL, failed_at datetime NULL, last_error text NULL, created_at datetime NOT NULL, updated_at datetime NOT NULL, PRIMARY KEY (id), UNIQUE KEY idempotency_key (idempotency_key), KEY queue (status,available_at), KEY institute_id (institute_id)) $c;",
			"CREATE TABLE $ad (id bigint unsigned NOT NULL AUTO_INCREMENT, canonical_id varchar(40) NOT NULL, institute_id bigint unsigned NOT NULL, student_name varchar(190) NOT NULL, mobile varchar(20) NOT NULL, email varchar(190) NULL, course varchar(190) NOT NULL, level varchar(100) NOT NULL, class_type varchar(20) NOT NULL, preferred_timing varchar(100) NULL, admission_date date NOT NULL, total_fee decimal(12,2) NOT NULL DEFAULT 0, amount_paid decimal(12,2) NOT NULL DEFAULT 0, pending_amount decimal(12,2) NOT NULL DEFAULT 0, payment_status varchar(30) NOT NULL DEFAULT 'pending', payment_method varchar(30) NOT NULL DEFAULT 'upi', transaction_reference varchar(190) NULL, access_period varchar(20) NOT NULL DEFAULT '3_months', custom_access_end date NULL, admission_status varchar(30) NOT NULL DEFAULT 'admission_created', notes text NULL, student_id bigint unsigned NULL, created_by bigint unsigned NOT NULL, status varchar(20) NOT NULL DEFAULT 'active', created_at datetime NOT NULL, updated_at datetime NOT NULL, PRIMARY KEY (id), UNIQUE KEY canonical_id (canonical_id), KEY institute_mobile (institute_id,mobile), KEY institute_email (institute_id,email), KEY institute_status (institute_id,admission_status), KEY student_id (student_id), KEY admission_date (admission_date)) $c;",
			"CREATE TABLE $students (id bigint unsigned NOT NULL AUTO_INCREMENT, canonical_id varchar(40) NOT NULL, institute_id bigint unsigned NOT NULL, wp_user_id bigint unsigned NULL, name varchar(190) NOT NULL, mobile varchar(20) NOT NULL, email varchar(190) NULL, course varchar(190) NOT NULL, level varchar(100) NOT NULL, class_type varchar(20) NOT NULL, batch_id bigint unsigned NULL, teacher_id bigint unsigned NULL, admission_id bigint unsigned NOT NULL, admission_date date NOT NULL, access_start date NULL, access_end date NULL, fee_status varchar(30) NOT NULL DEFAULT 'pending', account_status varchar(30) NOT NULL DEFAULT 'not_linked', student_status varchar(30) NOT NULL DEFAULT 'approved', status varchar(20) NOT NULL DEFAULT 'active', created_at datetime NOT NULL, updated_at datetime NOT NULL, PRIMARY KEY (id), UNIQUE KEY canonical_id (canonical_id), UNIQUE KEY institute_admission (institute_id,admission_id), KEY institute_mobile (institute_id,mobile), KEY institute_email (institute_id,email), KEY institute_filters (institute_id,student_status,fee_status), KEY batch_id (batch_id), KEY teacher_id (teacher_id), KEY wp_user_id (wp_user_id)) $c;",
			"CREATE TABLE $payments (id bigint unsigned NOT NULL AUTO_INCREMENT, canonical_id varchar(40) NOT NULL, institute_id bigint unsigned NOT NULL, student_id bigint unsigned NULL, admission_id bigint unsigned NOT NULL, amount decimal(12,2) NOT NULL, payment_method varchar(30) NOT NULL, transaction_reference varchar(190) NULL, source_identifier varchar(190) NULL, payment_date date NOT NULL, verification_status varchar(20) NOT NULL DEFAULT 'pending', verified_by bigint unsigned NULL, verified_at datetime NULL, access_period varchar(20) NOT NULL DEFAULT '1_month', custom_access_end date NULL, access_applied_at datetime NULL, notes text NULL, status varchar(20) NOT NULL DEFAULT 'active', created_at datetime NOT NULL, updated_at datetime NOT NULL, PRIMARY KEY (id), UNIQUE KEY canonical_id (canonical_id), UNIQUE KEY institute_source (institute_id,source_identifier), KEY institute_verification (institute_id,verification_status), KEY student_id (student_id), KEY admission_id (admission_id), KEY transaction_reference (transaction_reference), KEY payment_date (payment_date)) $c;",
			"CREATE TABLE $access (id bigint unsigned NOT NULL AUTO_INCREMENT, institute_id bigint unsigned NOT NULL, student_id bigint unsigned NOT NULL, access_start date NULL, access_end date NULL, access_status varchar(20) NOT NULL DEFAULT 'pending', last_payment_id bigint unsigned NULL, status varchar(20) NOT NULL DEFAULT 'active', created_at datetime NOT NULL, updated_at datetime NOT NULL, PRIMARY KEY (id), UNIQUE KEY institute_student (institute_id,student_id), KEY institute_status (institute_id,access_status), KEY access_end (access_end), KEY last_payment_id (last_payment_id)) $c;",
			"CREATE TABLE $history (id bigint unsigned NOT NULL AUTO_INCREMENT, institute_id bigint unsigned NOT NULL, student_id bigint unsigned NOT NULL, access_id bigint unsigned NOT NULL, payment_id bigint unsigned NULL, change_type varchar(30) NOT NULL, old_start date NULL, old_end date NULL, new_start date NULL, new_end date NULL, notes text NULL, created_by bigint unsigned NULL, status varchar(20) NOT NULL DEFAULT 'recorded', created_at datetime NOT NULL, PRIMARY KEY (id), UNIQUE KEY payment_change (payment_id,change_type), KEY institute_student (institute_id,student_id), KEY access_id (access_id), KEY created_at (created_at)) $c;",
			"CREATE TABLE $teachers (id bigint unsigned NOT NULL AUTO_INCREMENT, canonical_id varchar(40) NOT NULL, institute_id bigint unsigned NOT NULL, wp_user_id bigint unsigned NULL, name varchar(190) NOT NULL, mobile varchar(20) NOT NULL, email varchar(190) NULL, teacher_status varchar(20) NOT NULL DEFAULT 'active', joining_date date NOT NULL, available_days varchar(50) NULL, available_start_time time NULL, available_end_time time NULL, maximum_daily_classes smallint unsigned NOT NULL DEFAULT 8, notes text NULL, status varchar(20) NOT NULL DEFAULT 'active', created_at datetime NOT NULL, updated_at datetime NOT NULL, PRIMARY KEY (id), UNIQUE KEY canonical_id (canonical_id), KEY institute_mobile (institute_id,mobile), KEY institute_status (institute_id,teacher_status), KEY wp_user_id (wp_user_id)) $c;",
			"CREATE TABLE $batches (id bigint unsigned NOT NULL AUTO_INCREMENT, canonical_id varchar(40) NOT NULL, institute_id bigint unsigned NOT NULL, batch_name varchar(190) NOT NULL, course varchar(190) NOT NULL, level varchar(100) NOT NULL, class_type varchar(20) NOT NULL, teacher_id bigint unsigned NULL, capacity smallint unsigned NOT NULL, days_of_week varchar(50) NOT NULL, start_time time NOT NULL, end_time time NOT NULL, start_date date NOT NULL, end_date date NULL, timezone varchar(64) NOT NULL, batch_status varchar(20) NOT NULL DEFAULT 'active', status varchar(20) NOT NULL DEFAULT 'active', created_at datetime NOT NULL, updated_at datetime NOT NULL, PRIMARY KEY (id), UNIQUE KEY canonical_id (canonical_id), KEY institute_status (institute_id,batch_status), KEY teacher_id (teacher_id), KEY schedule (institute_id,start_date,end_date)) $c;",
			"CREATE TABLE $batch_students (id bigint unsigned NOT NULL AUTO_INCREMENT, institute_id bigint unsigned NOT NULL, batch_id bigint unsigned NOT NULL, student_id bigint unsigned NOT NULL, assignment_key varchar(190) NOT NULL, assignment_status varchar(20) NOT NULL DEFAULT 'active', assigned_at datetime NOT NULL, removed_at datetime NULL, transferred_to_batch_id bigint unsigned NULL, created_by bigint unsigned NULL, status varchar(20) NOT NULL DEFAULT 'active', created_at datetime NOT NULL, updated_at datetime NOT NULL, PRIMARY KEY (id), UNIQUE KEY assignment_key (assignment_key), KEY institute_student (institute_id,student_id,assignment_status), KEY batch_status (batch_id,assignment_status), KEY transferred_to (transferred_to_batch_id)) $c;",
			"CREATE TABLE $classes (id bigint unsigned NOT NULL AUTO_INCREMENT, canonical_id varchar(40) NOT NULL, schedule_key varchar(190) NOT NULL, institute_id bigint unsigned NOT NULL, batch_id bigint unsigned NULL, student_id bigint unsigned NULL, teacher_id bigint unsigned NOT NULL, class_type varchar(20) NOT NULL, class_date date NOT NULL, start_datetime datetime NOT NULL, end_datetime datetime NOT NULL, timezone varchar(64) NOT NULL, meet_url varchar(500) NULL, external_event_id varchar(190) NULL, class_status varchar(20) NOT NULL DEFAULT 'scheduled', original_values longtext NULL, status varchar(20) NOT NULL DEFAULT 'active', created_at datetime NOT NULL, updated_at datetime NOT NULL, PRIMARY KEY (id), UNIQUE KEY canonical_id (canonical_id), UNIQUE KEY schedule_key (schedule_key), KEY institute_date (institute_id,class_date,class_status), KEY teacher_time (institute_id,teacher_id,start_datetime,end_datetime), KEY student_time (institute_id,student_id,start_datetime,end_datetime), KEY batch_date (batch_id,class_date)) $c;",
			"CREATE TABLE $rules (id bigint unsigned NOT NULL AUTO_INCREMENT, institute_id bigint unsigned NOT NULL, batch_id bigint unsigned NOT NULL, days_of_week varchar(50) NOT NULL, start_time time NOT NULL, end_time time NOT NULL, timezone varchar(64) NOT NULL, rule_status varchar(20) NOT NULL DEFAULT 'active', status varchar(20) NOT NULL DEFAULT 'active', created_at datetime NOT NULL, updated_at datetime NOT NULL, PRIMARY KEY (id), UNIQUE KEY institute_batch (institute_id,batch_id), KEY rule_status (rule_status)) $c;",
			"CREATE TABLE $integrations (id bigint unsigned NOT NULL AUTO_INCREMENT, institute_id bigint unsigned NOT NULL, provider varchar(30) NOT NULL, client_id text NULL, client_secret_encrypted longtext NULL, access_token_encrypted longtext NULL, refresh_token_encrypted longtext NULL, token_expires_at datetime NULL, connected_account varchar(190) NULL, calendar_id varchar(190) NULL, connection_status varchar(20) NOT NULL DEFAULT 'disconnected', last_tested_at datetime NULL, last_error text NULL, status varchar(20) NOT NULL DEFAULT 'active', created_at datetime NOT NULL, updated_at datetime NOT NULL, PRIMARY KEY (id), UNIQUE KEY institute_provider (institute_id,provider), KEY connection_status (connection_status)) $c;",
			"CREATE TABLE $google_events (id bigint unsigned NOT NULL AUTO_INCREMENT, institute_id bigint unsigned NOT NULL, lecture_id bigint unsigned NOT NULL, sync_key varchar(190) NOT NULL, google_event_id varchar(190) NULL, google_calendar_id varchar(190) NULL, google_meet_url varchar(500) NULL, google_event_url varchar(500) NULL, sync_status varchar(20) NOT NULL DEFAULT 'pending', sync_action varchar(20) NOT NULL DEFAULT 'upsert', sync_attempts smallint unsigned NOT NULL DEFAULT 0, last_synced_at datetime NULL, last_error text NULL, status varchar(20) NOT NULL DEFAULT 'active', created_at datetime NOT NULL, updated_at datetime NOT NULL, PRIMARY KEY (id), UNIQUE KEY institute_lecture (institute_id,lecture_id), UNIQUE KEY sync_key (sync_key), UNIQUE KEY institute_google_event (institute_id,google_event_id), KEY institute_status (institute_id,sync_status), KEY last_synced_at (last_synced_at)) $c;",
			"CREATE TABLE $demo_sessions (id bigint unsigned NOT NULL AUTO_INCREMENT, canonical_id varchar(40) NOT NULL, session_key varchar(64) NOT NULL, institute_id bigint unsigned NOT NULL, demo_date date NOT NULL, start_time time NOT NULL, end_time time NOT NULL, teacher_id bigint unsigned NOT NULL, capacity smallint unsigned NOT NULL DEFAULT 6, lecture_id bigint unsigned NOT NULL, session_status varchar(20) NOT NULL DEFAULT 'scheduled', status varchar(20) NOT NULL DEFAULT 'active', created_by bigint unsigned NOT NULL, created_at datetime NOT NULL, updated_at datetime NOT NULL, PRIMARY KEY (id), UNIQUE KEY canonical_id (canonical_id), UNIQUE KEY session_key (session_key), UNIQUE KEY canonical_slot (institute_id,demo_date,start_time,end_time,teacher_id), UNIQUE KEY institute_lecture (institute_id,lecture_id), KEY institute_date (institute_id,demo_date,session_status), KEY teacher_slot (institute_id,teacher_id,demo_date,start_time,end_time)) $c;",
			"CREATE TABLE $demo_bookings (id bigint unsigned NOT NULL AUTO_INCREMENT, institute_id bigint unsigned NOT NULL, session_id bigint unsigned NOT NULL, booking_key varchar(190) NOT NULL, prospect_name varchar(190) NOT NULL, mobile varchar(20) NOT NULL, email varchar(190) NULL, attendance_status varchar(20) NOT NULL DEFAULT 'pending', feedback text NULL, follow_up_status varchar(30) NOT NULL DEFAULT 'pending', conversion_status varchar(30) NOT NULL DEFAULT 'not_converted', admission_id bigint unsigned NULL, booking_status varchar(20) NOT NULL DEFAULT 'booked', previous_session_id bigint unsigned NULL, moved_at datetime NULL, status varchar(20) NOT NULL DEFAULT 'active', created_by bigint unsigned NOT NULL, created_at datetime NOT NULL, updated_at datetime NOT NULL, PRIMARY KEY (id), UNIQUE KEY booking_key (booking_key), KEY institute_session (institute_id,session_id,booking_status), KEY institute_mobile (institute_id,mobile), KEY previous_session_id (previous_session_id), KEY follow_up_status (follow_up_status), KEY conversion_status (conversion_status), KEY admission_id (admission_id)) $c;",
			"CREATE TABLE $user_links (id bigint unsigned NOT NULL AUTO_INCREMENT, institute_id bigint unsigned NOT NULL, entity_type varchar(20) NOT NULL, entity_id bigint unsigned NOT NULL, wp_user_id bigint unsigned NOT NULL, canonical_hash char(64) NOT NULL, email_hash char(64) NULL, mobile_hash char(64) NULL, link_status varchar(20) NOT NULL DEFAULT 'active', linked_by bigint unsigned NOT NULL, linked_at datetime NOT NULL, status varchar(20) NOT NULL DEFAULT 'active', created_at datetime NOT NULL, updated_at datetime NOT NULL, PRIMARY KEY (id), UNIQUE KEY institute_entity (institute_id,entity_type,entity_id), UNIQUE KEY wp_user_entity (wp_user_id,entity_type), UNIQUE KEY canonical_lookup (institute_id,entity_type,canonical_hash), UNIQUE KEY email_lookup (institute_id,entity_type,email_hash), UNIQUE KEY mobile_lookup (institute_id,entity_type,mobile_hash), KEY institute_user (institute_id,wp_user_id), KEY link_status (link_status)) $c;",
			"CREATE TABLE $notifications (id bigint unsigned NOT NULL AUTO_INCREMENT, institute_id bigint unsigned NOT NULL, recipient_type varchar(20) NOT NULL, recipient_id bigint unsigned NOT NULL, wp_user_id bigint unsigned NULL, notification_type varchar(50) NOT NULL, event_type varchar(50) NULL, idempotency_key varchar(190) NOT NULL, title varchar(190) NOT NULL, message text NOT NULL, channels varchar(100) NOT NULL DEFAULT 'portal', channel varchar(20) NOT NULL DEFAULT 'portal', channel_payload longtext NULL, recipient_address varchar(190) NULL, entity_type varchar(50) NULL, entity_id varchar(100) NULL, notification_status varchar(20) NOT NULL DEFAULT 'pending', scheduled_at datetime NULL, sent_at datetime NULL, read_at datetime NULL, available_at datetime NOT NULL, failure_reason text NULL, status varchar(20) NOT NULL DEFAULT 'active', created_at datetime NOT NULL, updated_at datetime NOT NULL, PRIMARY KEY (id), UNIQUE KEY idempotency_key (idempotency_key), KEY institute_recipient (institute_id,recipient_type,recipient_id,notification_status), KEY wp_user_status (wp_user_id,notification_status), KEY queue (channel,notification_status,scheduled_at), KEY available_at (available_at), KEY notification_type (notification_type)) $c;",
			"CREATE TABLE $attendance (id bigint unsigned NOT NULL AUTO_INCREMENT, canonical_id varchar(40) NOT NULL, institute_id bigint unsigned NOT NULL, lecture_id bigint unsigned NULL, student_id bigint unsigned NULL, batch_id bigint unsigned NULL, demo_session_id bigint unsigned NULL, demo_booking_id bigint unsigned NULL, attendance_status varchar(20) NOT NULL DEFAULT 'not_marked', join_time datetime NULL, leave_time datetime NULL, minutes_attended smallint unsigned NULL, marked_by bigint unsigned NOT NULL, marked_at datetime NOT NULL, notes text NULL, status varchar(20) NOT NULL DEFAULT 'active', created_at datetime NOT NULL, updated_at datetime NOT NULL, PRIMARY KEY (id), UNIQUE KEY canonical_id (canonical_id), UNIQUE KEY lecture_student (institute_id,lecture_id,student_id), UNIQUE KEY demo_booking (institute_id,demo_booking_id), KEY institute_status (institute_id,attendance_status), KEY institute_marked (institute_id,marked_at), KEY lecture_id (lecture_id), KEY student_id (student_id), KEY batch_id (batch_id), KEY demo_session_id (demo_session_id)) $c;",
			"CREATE TABLE $migration_runs (id bigint unsigned NOT NULL AUTO_INCREMENT, run_key varchar(64) NOT NULL, institute_id bigint unsigned NOT NULL, mode varchar(20) NOT NULL, source_key varchar(100) NOT NULL, entity_types text NOT NULL, cursor_value bigint unsigned NOT NULL DEFAULT 0, batch_size smallint unsigned NOT NULL DEFAULT 100, processed bigint unsigned NOT NULL DEFAULT 0, created_count bigint unsigned NOT NULL DEFAULT 0, linked_count bigint unsigned NOT NULL DEFAULT 0, updated_count bigint unsigned NOT NULL DEFAULT 0, skipped_count bigint unsigned NOT NULL DEFAULT 0, duplicate_count bigint unsigned NOT NULL DEFAULT 0, conflict_count bigint unsigned NOT NULL DEFAULT 0, failed_count bigint unsigned NOT NULL DEFAULT 0, started_by bigint unsigned NOT NULL, started_at datetime NOT NULL, finished_at datetime NULL, run_status varchar(20) NOT NULL DEFAULT 'pending', last_error text NULL, backup_confirmed tinyint(1) NOT NULL DEFAULT 0, status varchar(20) NOT NULL DEFAULT 'active', created_at datetime NOT NULL, updated_at datetime NOT NULL, PRIMARY KEY (id), UNIQUE KEY run_key (run_key), KEY institute_status (institute_id,run_status), KEY source_key (source_key), KEY started_at (started_at)) $c;",
			"CREATE TABLE $migration_conflicts (id bigint unsigned NOT NULL AUTO_INCREMENT, institute_id bigint unsigned NOT NULL, run_id bigint unsigned NOT NULL, source_key varchar(100) NOT NULL, source_table varchar(190) NOT NULL, source_id varchar(190) NOT NULL, entity_type varchar(50) NOT NULL, conflict_type varchar(50) NOT NULL, source_fingerprint char(64) NULL, source_summary longtext NULL, canonical_summary longtext NULL, reason text NOT NULL, resolution varchar(30) NULL, resolved_target_id bigint unsigned NULL, resolved_by bigint unsigned NULL, resolved_at datetime NULL, conflict_status varchar(20) NOT NULL DEFAULT 'open', status varchar(20) NOT NULL DEFAULT 'active', created_at datetime NOT NULL, updated_at datetime NOT NULL, PRIMARY KEY (id), UNIQUE KEY run_source_conflict (run_id,source_key,source_table,source_id,conflict_type), KEY institute_status (institute_id,conflict_status), KEY run_id (run_id), KEY source_record (source_key,source_table,source_id)) $c;"
		);
		foreach ( $sql as $statement ) { dbDelta( $statement ); }
	}
}
