<?php
defined( 'ABSPATH' ) || exit;

final class EduFlow_Notification_Service {
	const TYPES=array('admission_approved','payment_verified','access_activated','access_expiring','access_expired','student_assigned','teacher_changed','class_scheduled','class_rescheduled','class_cancelled','meet_ready','demo_scheduled','demo_rescheduled','demo_cancelled','demo_follow_up_due','attendance_marked','student_absent','renewal_reminder');
	const STATUSES=array('pending','queued','sent','failed','read','cancelled');
	public static function create($type,$recipient_type,$recipient_id,$title,$message,$dedupe_key,$entity_type=null,$entity_id=null,$channels=array('portal'),$institute_id=0){
		global $wpdb;$type=sanitize_key($type);$recipient_type=sanitize_key($recipient_type);if(!in_array($type,self::TYPES,true)||!in_array($recipient_type,array('student','teacher','manager','demo_booking'),true)){return new WP_Error('invalid_notification','Invalid notification type or recipient.');}$institute_id=$institute_id?:EduFlow_Settings::institute_db_id();$channels=array_values(array_intersect(array('portal','email_ready','whatsapp_ready'),array_map('sanitize_key',(array)$channels)));if(!$channels){$channels=array('portal');}$link=in_array($recipient_type,array('student','teacher'),true)?self::link_for_entity($recipient_type,$recipient_id,$institute_id):null;$now=current_time('mysql',true);$key=hash('sha256',$institute_id.'|'.sanitize_text_field($dedupe_key));$data=array('institute_id'=>$institute_id,'recipient_type'=>$recipient_type,'recipient_id'=>absint($recipient_id),'wp_user_id'=>$link?$link['wp_user_id']:null,'notification_type'=>$type,'event_type'=>$type,'idempotency_key'=>$key,'title'=>sanitize_text_field($title),'message'=>sanitize_textarea_field($message),'channels'=>implode(',',$channels),'channel'=>'portal','entity_type'=>$entity_type?sanitize_key($entity_type):null,'entity_id'=>null===$entity_id?null:sanitize_text_field((string)$entity_id),'notification_status'=>'pending','scheduled_at'=>$now,'available_at'=>$now,'status'=>'active','created_at'=>$now,'updated_at'=>$now);
		$result=$wpdb->insert(EduFlow_DB::table('notifications'),$data);if(false===$result){$existing=method_exists($wpdb,'get_var')?$wpdb->get_var($wpdb->prepare('SELECT id FROM '.EduFlow_DB::table('notifications').' WHERE idempotency_key=%s',$key)):0;return $existing?(int)$existing:new WP_Error('duplicate_notification','Notification already exists or could not be created.');}$id=(int)$wpdb->insert_id;if(class_exists('EduFlow_Job_Service')){EduFlow_Job_Service::enqueue('notification_dispatch',array('notification_id'=>$id,'institute_id'=>$institute_id),'notification:'.$id,$institute_id);}return $id;
	}
	private static function link_for_entity($type,$entity_id,$institute_id){global $wpdb;$table=EduFlow_DB::table('user_links');return $wpdb->get_row($wpdb->prepare("SELECT wp_user_id FROM $table WHERE institute_id=%d AND entity_type=%s AND entity_id=%d AND link_status='active'",$institute_id,$type,$entity_id),ARRAY_A);}
	public static function for_user($user_id=0,$limit=20,$institute_id=0){global $wpdb;$user_id=$user_id?:get_current_user_id();$link=EduFlow_Account_Link_Service::linked_entity_any_institute('student',$user_id)?:EduFlow_Account_Link_Service::linked_entity_any_institute('teacher',$user_id);$institute_id=$institute_id?:($link?(int)$link['institute_id']:EduFlow_Settings::institute_db_id());$table=EduFlow_DB::table('notifications');return $wpdb->get_results($wpdb->prepare("SELECT id,event_type AS notification_type,title,message,notification_status,entity_type,entity_id,created_at,read_at FROM $table WHERE institute_id=%d AND wp_user_id=%d AND status='active' AND available_at<=%s ORDER BY created_at DESC LIMIT %d",$institute_id,$user_id,current_time('mysql',true),min(100,max(1,absint($limit)))),ARRAY_A);}
	public static function unread_count($user_id=0,$institute_id=0){global $wpdb;$user_id=$user_id?:get_current_user_id();$link=EduFlow_Account_Link_Service::linked_entity_any_institute('student',$user_id)?:EduFlow_Account_Link_Service::linked_entity_any_institute('teacher',$user_id);$institute_id=$institute_id?:($link?(int)$link['institute_id']:EduFlow_Settings::institute_db_id());return (int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM ".EduFlow_DB::table('notifications')." WHERE institute_id=%d AND wp_user_id=%d AND notification_status IN ('pending','queued','sent') AND read_at IS NULL AND status='active'",$institute_id,$user_id));}
	public static function mark_read($id,$user_id=0,$institute_id=0){global $wpdb;$user_id=$user_id?:get_current_user_id();$link=EduFlow_Account_Link_Service::linked_entity_any_institute('student',$user_id)?:EduFlow_Account_Link_Service::linked_entity_any_institute('teacher',$user_id);$institute_id=$institute_id?:($link?(int)$link['institute_id']:EduFlow_Settings::institute_db_id());return $wpdb->update(EduFlow_DB::table('notifications'),array('notification_status'=>'read','read_at'=>current_time('mysql',true),'updated_at'=>current_time('mysql',true)),array('id'=>absint($id),'institute_id'=>$institute_id,'wp_user_id'=>$user_id,'status'=>'active'));}
	public static function attendance($student_id,$lecture_id,$status,$institute_id){$title='Attendance marked';$message='Attendance for your lecture was marked '.str_replace('_',' ',$status).'.';self::create('attendance_marked','student',$student_id,$title,$message,'attendance:'.$lecture_id.':'.$student_id.':'.$status,'class',$lecture_id,array('portal','email_ready','whatsapp_ready'),$institute_id);if('absent'===$status){self::create('student_absent','student',$student_id,'Class absence recorded',$message,'absence:'.$lecture_id.':'.$student_id,'class',$lecture_id,array('portal','email_ready','whatsapp_ready'),$institute_id);}}
	public static function notify_class($lecture_id,$type,$title,$message,$revision,$institute_id){global $wpdb;$lecture=EduFlow_Class_Service::get($lecture_id,$institute_id);if(!$lecture){return;}self::create($type,'teacher',$lecture['teacher_id'],$title,$message,$type.':'.$lecture_id.':teacher:'.$revision,'class',$lecture_id,array('portal','email_ready'),$institute_id);$ids=$lecture['student_id']?array($lecture['student_id']):($lecture['batch_id']?$wpdb->get_col($wpdb->prepare("SELECT student_id FROM ".EduFlow_DB::table('batch_students')." WHERE institute_id=%d AND batch_id=%d AND assignment_status='active'",$institute_id,$lecture['batch_id'])):array());foreach($ids as $id){self::create($type,'student',$id,$title,$message,$type.':'.$lecture_id.':student:'.$id.':'.$revision,'class',$lecture_id,array('portal','email_ready','whatsapp_ready'),$institute_id);}}
	public static function retry($id,$institute_id=0){global $wpdb;$institute_id=$institute_id?:EduFlow_Settings::institute_db_id();$updated=$wpdb->update(EduFlow_DB::table('notifications'),array('notification_status'=>'pending','failure_reason'=>null,'updated_at'=>current_time('mysql',true)),array('id'=>absint($id),'institute_id'=>$institute_id,'notification_status'=>'failed'));if($updated){EduFlow_Job_Service::enqueue('notification_dispatch',array('notification_id'=>absint($id),'institute_id'=>$institute_id),'notification-retry:'.absint($id).':'.time(),$institute_id);EduFlow_Audit_Service::log('notification_retried','notification',$id,null,array('status'=>'pending'),$institute_id);}return $updated;}
	public static function cancel($id,$institute_id=0){global $wpdb;$institute_id=$institute_id?:EduFlow_Settings::institute_db_id();$updated=$wpdb->update(EduFlow_DB::table('notifications'),array('notification_status'=>'cancelled','updated_at'=>current_time('mysql',true)),array('id'=>absint($id),'institute_id'=>$institute_id));if($updated){EduFlow_Audit_Service::log('notification_cancelled','notification',$id,null,array('status'=>'cancelled'),$institute_id);}return $updated;}
	public static function generate_due($institute_id=0){global $wpdb;$institute_id=$institute_id?:EduFlow_Settings::institute_db_id();$today=current_time('Y-m-d');$soon=gmdate('Y-m-d',strtotime($today.' +7 days'));$rows=$wpdb->get_results($wpdb->prepare("SELECT id,student_id,access_end FROM ".EduFlow_DB::table('access')." WHERE institute_id=%d AND access_status='active' AND access_end BETWEEN %s AND %s",$institute_id,$today,$soon),ARRAY_A);foreach($rows as $row){self::create('access_expiring','student',$row['student_id'],'Access expiring','Your learning access expires on '.$row['access_end'].'.','access-expiring:'.$row['id'].':'.$row['access_end'],'access',$row['id'],array('portal','email_ready','whatsapp_ready'),$institute_id);self::create('renewal_reminder','student',$row['student_id'],'Renewal reminder','Please contact your institute about renewal.','renewal:'.$row['id'].':'.$row['access_end'],'access',$row['id'],array('portal','email_ready','whatsapp_ready'),$institute_id);}}
}
