<?php
defined( 'ABSPATH' ) || exit;

final class EduFlow_Access_Service {
	public static function calculate_end( $base_date, $period, $custom_end=null ) {
		$base=new DateTimeImmutable($base_date); if('custom'===$period){$custom=DateTimeImmutable::createFromFormat('Y-m-d',(string)$custom_end);if(!$custom||$custom<$base){return new WP_Error('invalid_access_end','Custom end date must not precede the activation date.');}return $custom->format('Y-m-d');}
		$months=array('1_month'=>1,'3_months'=>3,'6_months'=>6);if(!isset($months[$period])){return new WP_Error('invalid_access_period','Invalid access period.');}return $base->modify('+'.$months[$period].' months')->format('Y-m-d');
	}
	public static function apply_verified_payment( $payment, $activation_date=null ) {
		global $wpdb;$institute_id=(int)$payment['institute_id'];$student_id=(int)$payment['student_id'];if(!$student_id){return new WP_Error('student_required','Link a student before activating access.');}$table=EduFlow_DB::table('access');$history=EduFlow_DB::table('access_history');$students=EduFlow_DB::table('students');$today=$activation_date?:current_time('Y-m-d');
		$access=$wpdb->get_row($wpdb->prepare("SELECT * FROM $table WHERE institute_id=%d AND student_id=%d FOR UPDATE",$institute_id,$student_id),ARRAY_A);$base=$today;$type='activation';if($access&&!empty($access['access_end'])&&$access['access_end']>=$today){$base=$access['access_end'];$type='extension';}$end=self::calculate_end($base,$payment['access_period'],$payment['custom_access_end']);if(is_wp_error($end)){return $end;}$now=current_time('mysql',true);
		if($access){$access_id=(int)$access['id'];$wpdb->update($table,array('access_start'=>$access['access_start']?:$today,'access_end'=>$end,'access_status'=>'active','last_payment_id'=>$payment['id'],'updated_at'=>$now),array('id'=>$access_id,'institute_id'=>$institute_id));}else{$wpdb->insert($table,array('institute_id'=>$institute_id,'student_id'=>$student_id,'access_start'=>$today,'access_end'=>$end,'access_status'=>'active','last_payment_id'=>$payment['id'],'status'=>'active','created_at'=>$now,'updated_at'=>$now));$access_id=(int)$wpdb->insert_id;}
		$insert=$wpdb->insert($history,array('institute_id'=>$institute_id,'student_id'=>$student_id,'access_id'=>$access_id,'payment_id'=>$payment['id'],'change_type'=>$type,'old_start'=>$access['access_start']??null,'old_end'=>$access['access_end']??null,'new_start'=>$access['access_start']??$today,'new_end'=>$end,'created_by'=>get_current_user_id(),'status'=>'recorded','created_at'=>$now));if(false===$insert){return new WP_Error('access_already_applied','This payment has already changed access.');}
		$wpdb->update($students,array('access_start'=>$access['access_start']??$today,'access_end'=>$end,'fee_status'=>'paid','student_status'=>'active','updated_at'=>$now),array('id'=>$student_id,'institute_id'=>$institute_id));EduFlow_Audit_Service::log('access_'.$type,'student_access',$student_id,$access,array('access_end'=>$end),$institute_id);EduFlow_Notification_Service::create('access_activated','student',$student_id,'Access updated','Your learning access is active through '.$end,'access:'.$payment['id'],'payment',$payment['id'],array('portal','email_ready','whatsapp_ready'),$institute_id);return true;
	}
	public static function expire_due() { global $wpdb;$today=current_time('Y-m-d');$table=EduFlow_DB::table('access');$rows=$wpdb->get_results($wpdb->prepare("SELECT * FROM $table WHERE access_status=%s AND access_end<%s LIMIT 100",'active',$today),ARRAY_A);foreach($rows as $row){$changed=$wpdb->update($table,array('access_status'=>'expired','updated_at'=>current_time('mysql',true)),array('id'=>$row['id'],'institute_id'=>$row['institute_id'],'access_status'=>'active'));if($changed){EduFlow_Audit_Service::log('access_expired','student_access',$row['student_id'],$row,array('access_status'=>'expired'),$row['institute_id']);EduFlow_Notification_Service::create('access_expired','student',$row['student_id'],'Access expired','Your learning access has expired.','access-expired:'.$row['id'].':'.$row['access_end'],'access',$row['id'],array('portal','email_ready','whatsapp_ready'),$row['institute_id']);}}return count($rows); }
	public static function manual_adjust( $student_id, $new_end, $new_status='active', $notes='', $institute_id=0 ) {
		global $wpdb;$institute_id=$institute_id?:EduFlow_Settings::institute_db_id();if(!in_array($new_status,array('pending','active','expired','paused','cancelled'),true)){return new WP_Error('invalid_access_status','Invalid access status.');}$date=DateTimeImmutable::createFromFormat('Y-m-d',(string)$new_end);if(!$date||$date->format('Y-m-d')!==$new_end){return new WP_Error('invalid_access_end','Invalid access end date.');}$table=EduFlow_DB::table('access');$history=EduFlow_DB::table('access_history');$wpdb->query('START TRANSACTION');$old=$wpdb->get_row($wpdb->prepare("SELECT * FROM $table WHERE institute_id=%d AND student_id=%d FOR UPDATE",$institute_id,$student_id),ARRAY_A);if(!$old){$wpdb->query('ROLLBACK');return new WP_Error('access_not_found','Access record not found.');}$now=current_time('mysql',true);$wpdb->update($table,array('access_end'=>$new_end,'access_status'=>$new_status,'updated_at'=>$now),array('id'=>$old['id'],'institute_id'=>$institute_id));$wpdb->insert($history,array('institute_id'=>$institute_id,'student_id'=>$student_id,'access_id'=>$old['id'],'change_type'=>'manual_adjustment','old_start'=>$old['access_start'],'old_end'=>$old['access_end'],'new_start'=>$old['access_start'],'new_end'=>$new_end,'notes'=>sanitize_textarea_field($notes),'created_by'=>get_current_user_id(),'status'=>'recorded','created_at'=>$now));$wpdb->query('COMMIT');EduFlow_Audit_Service::log('access_manually_changed','student_access',$student_id,$old,array('access_end'=>$new_end,'access_status'=>$new_status),$institute_id);return true;
	}

}
