<?php
defined( 'ABSPATH' ) || exit;

final class EduFlow_Payment_Service {
	const METHODS=array('upi','cash','bank_transfer','card','other');
	public static function create( $input, $institute_id=0 ) {
		global $wpdb;$institute_id=$institute_id?:EduFlow_Settings::institute_db_id();$method=sanitize_key($input['payment_method']??'');if(!in_array($method,self::METHODS,true)){return new WP_Error('invalid_method','Invalid payment method.');}$amount=round((float)($input['amount']??0),2);if($amount<=0){return new WP_Error('invalid_amount','Amount must be greater than zero.');}$admission_id=absint($input['admission_id']??0);$admission=EduFlow_Admission_Service::get($admission_id,$institute_id);if(!$admission){return new WP_Error('invalid_admission','Admission not found.');}$student_id=absint($input['student_id']??$admission['student_id']);if($student_id&&!EduFlow_Student_Service::get($student_id,$institute_id)){return new WP_Error('invalid_student','Student not found.');}
		$source=sanitize_text_field($input['source_identifier']??'');$reference=sanitize_text_field($input['transaction_reference']??'');if(''===$source&&''!==$reference){$source='manual:'.$method.':'.strtolower($reference);}$canonical=EduFlow_ID_Service::generate('payment',$institute_id);if(is_wp_error($canonical)){return $canonical;}$now=current_time('mysql',true);$period=sanitize_key($input['access_period']??'1_month');$data=array('canonical_id'=>$canonical,'institute_id'=>$institute_id,'student_id'=>$student_id?:null,'admission_id'=>$admission_id,'amount'=>$amount,'payment_method'=>$method,'transaction_reference'=>$reference?:null,'source_identifier'=>$source?:null,'payment_date'=>sanitize_text_field($input['payment_date']??current_time('Y-m-d')),'verification_status'=>'pending','access_period'=>$period,'custom_access_end'=>sanitize_text_field($input['custom_access_end']??'')?:null,'notes'=>sanitize_textarea_field($input['notes']??''),'status'=>'active','created_at'=>$now,'updated_at'=>$now);if(false===$wpdb->insert(EduFlow_DB::table('payments'),$data)){return new WP_Error('payment_create_failed','Payment is duplicate or could not be created.');}$wpdb->update(EduFlow_DB::table('admissions'),array('admission_status'=>'payment_verification','updated_at'=>$now),array('id'=>$admission_id,'institute_id'=>$institute_id,'admission_status'=>'admission_created'));EduFlow_Audit_Service::log('payment_created','payment',$canonical,null,$data,$institute_id);return(int)$wpdb->insert_id;
	}
	public static function get($id,$institute_id=0,$lock=false){global $wpdb;$table=EduFlow_DB::table('payments');$institute_id=$institute_id?:EduFlow_Settings::institute_db_id();return $wpdb->get_row($wpdb->prepare("SELECT * FROM $table WHERE id=%d AND institute_id=%d".($lock?' FOR UPDATE':''),$id,$institute_id),ARRAY_A);}
	public static function decide($id,$decision,$institute_id=0){global $wpdb;$institute_id=$institute_id?:EduFlow_Settings::institute_db_id();if(!in_array($decision,array('verified','rejected','refunded'),true)){return new WP_Error('invalid_decision','Invalid payment decision.');}$table=EduFlow_DB::table('payments');$wpdb->query('START TRANSACTION');try{$payment=self::get($id,$institute_id,true);if(!$payment){throw new RuntimeException('Payment not found.');}if($payment['verification_status']===$decision){$wpdb->query('COMMIT');return true;}if('pending'!==$payment['verification_status']){throw new RuntimeException('Payment has already been decided.');}$now=current_time('mysql',true);if('verified'===$decision&&$payment['student_id']){$result=EduFlow_Access_Service::apply_verified_payment($payment,$payment['payment_date']);if(is_wp_error($result)){throw new RuntimeException($result->get_error_message());}}$wpdb->update($table,array('verification_status'=>$decision,'verified_by'=>get_current_user_id(),'verified_at'=>$now,'access_applied_at'=>('verified'===$decision&&$payment['student_id'])?$now:null,'updated_at'=>$now),array('id'=>$id,'institute_id'=>$institute_id,'verification_status'=>'pending'));$ad=EduFlow_DB::table('admissions');if('verified'===$decision){if(0===strpos((string)$payment['source_identifier'],'admission_initial:')){$wpdb->query($wpdb->prepare("UPDATE $ad SET pending_amount=GREATEST(total_fee-amount_paid,0),payment_status=IF(amount_paid>=total_fee,'paid',IF(amount_paid>0,'partial','pending')),admission_status=IF(admission_status='payment_verification','approved',admission_status),updated_at=%s WHERE id=%d AND institute_id=%d",$now,$payment['admission_id'],$institute_id));}else{$wpdb->query($wpdb->prepare("UPDATE $ad SET amount_paid=amount_paid+%f,pending_amount=GREATEST(total_fee-(amount_paid+%f),0),payment_status=IF(amount_paid+%f>=total_fee,'paid','partial'),admission_status=IF(admission_status='payment_verification','approved',admission_status),updated_at=%s WHERE id=%d AND institute_id=%d",$payment['amount'],$payment['amount'],$payment['amount'],$now,$payment['admission_id'],$institute_id));}}$wpdb->query('COMMIT');EduFlow_Audit_Service::log('payment_'.$decision,'payment',$payment['canonical_id'],$payment['verification_status'],$decision,$institute_id);if('verified'===$decision&&$payment['student_id']){EduFlow_Notification_Service::create('payment_verified','student',$payment['student_id'],'Payment verified','Your payment has been verified.','payment-verified:'.$id,'payment',$id,array('portal','email_ready','whatsapp_ready'),$institute_id);}return true;}catch(Throwable $e){$wpdb->query('ROLLBACK');return new WP_Error('payment_decision_failed',$e->getMessage());}}
}
