<?php
defined( 'ABSPATH' ) || exit;

final class EduFlow_Student_Service {
	public static function convert_admission( $admission_id, $institute_id = 0 ) {
		global $wpdb; $institute_id=$institute_id?:EduFlow_Settings::institute_db_id(); $admissions=EduFlow_DB::table('admissions'); $students=EduFlow_DB::table('students'); $wpdb->query('START TRANSACTION');
		try {
			$admission=EduFlow_Admission_Service::get($admission_id,$institute_id,true); if(!$admission){throw new RuntimeException('Admission not found.');}
			$existing=$wpdb->get_var($wpdb->prepare("SELECT id FROM $students WHERE institute_id=%d AND admission_id=%d",$institute_id,$admission_id));
			if($existing){$wpdb->query('COMMIT');return (int)$existing;}
			if(!in_array($admission['admission_status'],array('approved','active'),true)){throw new RuntimeException('Approve the admission before conversion.');}
			$canonical=EduFlow_ID_Service::generate('student',$institute_id); if(is_wp_error($canonical)){throw new RuntimeException($canonical->get_error_message());}
			$now=current_time('mysql',true); $data=array('canonical_id'=>$canonical,'institute_id'=>$institute_id,'wp_user_id'=>null,'name'=>$admission['student_name'],'mobile'=>$admission['mobile'],'email'=>$admission['email']?:null,'course'=>$admission['course'],'level'=>$admission['level'],'class_type'=>$admission['class_type'],'batch_id'=>null,'teacher_id'=>null,'admission_id'=>$admission_id,'admission_date'=>$admission['admission_date'],'fee_status'=>$admission['payment_status'],'account_status'=>'not_linked','student_status'=>'approved','status'=>'active','created_at'=>$now,'updated_at'=>$now);
			if(false===$wpdb->insert($students,$data)){throw new RuntimeException('Student could not be created.');} $student_id=(int)$wpdb->insert_id;
			$wpdb->update($admissions,array('student_id'=>$student_id,'admission_status'=>'active','updated_at'=>$now),array('id'=>$admission_id,'institute_id'=>$institute_id),array('%d','%s','%s'),array('%d','%d'));
			$payments=EduFlow_DB::table('payments');$pending=$wpdb->get_results($wpdb->prepare("SELECT * FROM $payments WHERE institute_id=%d AND admission_id=%d AND verification_status='verified' AND access_applied_at IS NULL FOR UPDATE",$institute_id,$admission_id),ARRAY_A);foreach($pending as $payment){$payment['student_id']=$student_id;$applied=EduFlow_Access_Service::apply_verified_payment($payment,$payment['payment_date']);if(is_wp_error($applied)){throw new RuntimeException($applied->get_error_message());}$wpdb->update($payments,array('student_id'=>$student_id,'access_applied_at'=>$now,'updated_at'=>$now),array('id'=>$payment['id'],'institute_id'=>$institute_id));}
			$wpdb->query('COMMIT'); EduFlow_Audit_Service::log('student_created','student',$canonical,null,$data,$institute_id); EduFlow_Notification_Service::create('admission_approved','student',$student_id,'Admission approved','Your admission has been approved.','admission-approved:'.$admission_id,'admission',$admission_id,array('portal','email_ready','whatsapp_ready'),$institute_id); return $student_id;
		} catch(Throwable $e){$wpdb->query('ROLLBACK');return new WP_Error('student_conversion_failed',$e->getMessage());}
	}
	public static function get( $id, $institute_id=0, $lock=false ) { global $wpdb;$table=EduFlow_DB::table('students');$institute_id=$institute_id?:EduFlow_Settings::institute_db_id();return $wpdb->get_row($wpdb->prepare("SELECT * FROM $table WHERE id=%d AND institute_id=%d".($lock?' FOR UPDATE':''),$id,$institute_id),ARRAY_A); }
	public static function update( $id, $input, $institute_id=0 ) { global $wpdb;$institute_id=$institute_id?:EduFlow_Settings::institute_db_id();$old=self::get($id,$institute_id);if(!$old){return new WP_Error('not_found','Student not found.');}$mobile=EduFlow_Contact_Service::normalize_indian_mobile($input['mobile']??'');if(is_wp_error($mobile)){return $mobile;}$email=sanitize_email($input['email']??'');if(!empty($input['email'])&&!is_email($email)){return new WP_Error('invalid_email','Enter a valid email or leave it empty.');}$class=sanitize_key($input['class_type']??'');if(!in_array($class,EduFlow_Admission_Service::CLASS_TYPES,true)){return new WP_Error('invalid_class_type','Invalid class type.');}$data=array('name'=>sanitize_text_field($input['name']??''),'mobile'=>$mobile,'email'=>$email?:null,'course'=>sanitize_text_field($input['course']??''),'level'=>sanitize_text_field($input['level']??''),'class_type'=>$class,'batch_id'=>absint($input['batch_id']??0)?:null,'teacher_id'=>absint($input['teacher_id']??0)?:null,'student_status'=>sanitize_key($input['student_status']??$old['student_status']),'updated_at'=>current_time('mysql',true));$result=$wpdb->update(EduFlow_DB::table('students'),$data,array('id'=>$id,'institute_id'=>$institute_id));if(false===$result){return new WP_Error('student_update_failed','Student could not be updated.');}EduFlow_Audit_Service::log('student_updated','student',$old['canonical_id'],$old,$data,$institute_id);return true; }
	public static function query( $args=array(), $institute_id=0 ) {
		global $wpdb;$table=EduFlow_DB::table('students');$institute_id=$institute_id?:EduFlow_Settings::institute_db_id();$page=max(1,absint($args['paged']??1));$per=min(100,max(1,absint($args['per_page']??20)));$where=array('institute_id=%d');$params=array($institute_id);
		$search=sanitize_text_field($args['search']??'');if($search!==''){$like='%'.$wpdb->esc_like($search).'%';$where[]='(name LIKE %s OR canonical_id LIKE %s OR mobile LIKE %s OR email LIKE %s)';array_push($params,$like,$like,$like,$like);}
		foreach(array('course','level','class_type','student_status','fee_status') as $field){if(!empty($args[$field])){$where[]="$field=%s";$params[]=sanitize_text_field($args[$field]);}}
		$allowed=array('canonical_id','name','course','level','class_type','student_status','fee_status','access_end','created_at');$order=in_array($args['orderby']??'',$allowed,true)?$args['orderby']:'created_at';$direction='asc'===strtolower($args['order']??'')?'ASC':'DESC';$base=' FROM '.$table.' WHERE '.implode(' AND ',$where);$total=(int)$wpdb->get_var($wpdb->prepare('SELECT COUNT(*)'.$base,...$params));$params[]= $per;$params[]=($page-1)*$per;$items=$wpdb->get_results($wpdb->prepare("SELECT *$base ORDER BY $order $direction LIMIT %d OFFSET %d",...$params),ARRAY_A);return array('items'=>$items,'total'=>$total,'pages'=>(int)ceil($total/$per),'page'=>$page);
	}
}
